# These are supported funding model platforms

github: [anxlc, enqlea]
patreon: anxlc
open_collective: anxlc
ko_fi: anxlc
tidelift: # None
community_bridge: # None
liberapay: anxlc
issuehunt: anxlc
lfx_crowdfunding: anxlc
polar: # None
buy_me_a_coffee: anxlc
custom: # None
